name: wfi
channels:
  - conda-forge
  - bioconda
  - r
  - ammaraziz
dependencies:
  - snakemake
  - cutadapt
  - python=3.9
  - bbmap
  - r-base
  - r-optparse
  - r-ggplot2
  - r-stringr
  - r-dplyr
  - r-cowplot
  - r-gridExtra
  - r-furrr
  - ammaraziz::irma
  - r-tidyr
  pip:
    - icecream
    - pix
    - biopython=1.78

